version: 2.1

jobs:

  build-and-test:
    docker:
      - image: nfvri/golang-base:bookworm-1.20.6-2.10.0
    steps:
      - checkout
      - run: make clean
      - run: make gomodextras
      - run: make test-ci

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
                - develop

